export type Service = [string, string, ...string[]]

export const SERVICE_LIST: Service[] = [
    ['full', 'Full Rent', 'اجاره کامل'],
    ['tg', 'Telegram', 'تلگرام'],
    ['ig', 'Instagram+Threads', 'اینستاگرام'],
    ['go', 'Google,youtube,Gmail', 'گوگل'],
    ['mm', 'Microsoft', 'مایکروسافت'],
    ['wa', 'Whatsapp'],
    ['fb', 'facebook'],
    ['oi', 'Tinder'],
    ['lf', 'TikTok/Douyin'],
    ['ds', 'Discord'],
    ['hw', 'Alipay/Alibaba/1688'],
    ['tw', 'Twitter'],
    ['am', 'Amazon'],
    ['yw', 'Grindr'],
    ['ot', 'Any other'],
    ['ot', 'Any other call forwarding'],
    ['vk', 'vk.com'],
    ['pm', 'AOL'],
    ['uu', 'Wildberries'],
    ['li', 'Baidu'],
    ['wx', 'Apple'],
    ['ub', 'Uber'],
    ['ya', 'Yandex call forwarding'],
    ['ya', 'Yandex'],
    ['qq', 'Tencent QQ'],
    ['acz', 'Claude'],
    ['md', 'Банки'],
    ['bw', 'Signal'],
    ['of', 'urent/jet/RuSharing'],
    ['me', 'Line messenger'],
    ['mb', 'Yahoo'],
    ['nv', 'Naver'],
    ['ev', 'Picpay'],
    ['ft', 'Букмекерские'],
    ['kf', 'Weibo'],
    ['ok', 'ok.ru'],
    ['vi', 'Viber'],
    ['ts', 'PayPal'],
    ['ju', 'Indomaret'],
    ['sg', 'OZON'],
    ['ew', 'Nike'],
    ['dl', 'Lazada'],
    ['ki', '99app'],
    ['aqc', 'Omne by FWD'],
    ['ka', 'Shopee'],
    ['pc', 'Casino/bet/gambling'],
    ['wb', 'WeChat'],
    ['uk', 'Airbnb'],
    ['nz', 'Foodpanda'],
    ['bz', 'Blizzard'],
    ['qf', 'RedBook'],
    ['sn', 'OLX'],
    ['av', 'avito'],
    ['av', 'avito call forwarding'],
    ['yr', 'Miravia'],
    ['cq', 'Mercado'],
    ['dh', 'eBay'],
    ['jg', 'Grab'],
    ['ma', 'Mail.ru'],
    ['yl', 'Yalla'],
    ['ad', 'Iti'],
    ['kc', 'Vinted'],
    ['pf', 'pof.com'],
    ['kt', 'KakaoTalk'],
    ['tu', 'Lyft'],
    ['fu', 'Snapchat'],
    ['xj', 'СберМаркет'],
    ['vz', 'Hinge'],
    ['im', 'Imo'],
    ['zh', 'Zoho'],
    ['zk', 'Deliveroo'],
    ['afm', 'myboost'],
    ['fr', 'Dana'],
    ['ni', 'Gojek'],
    ['vy', 'Meta'],
    ['aqe', 'PeraMoo'],
    ['jr', 'Самокат'],
    ['ac', 'DoorDash'],
    ['mj', 'Zalo'],
    ['ax', 'CrefisaMais'],
    ['mg', 'Magnit'],
    ['abk', 'GMX'],
    ['pd', 'IFood'],
    ['mt', 'Steam'],
    ['bc', 'GCash'],
    ['fd', 'Mamba'],
    ['df', 'Happn'],
    ['dr', 'OpenAI'],
    ['gf', 'GoogleVoice'],
    ['aqb', 'Pinoy Peso'],
    ['ir', 'Chispa'],
    ['rr', 'Wolt'],
    ['tx', 'Bolt'],
    ['xm', 'Лэтуаль'],
    ['nf', 'Netflix'],
    ['my', 'CAIXA'],
    ['ym', 'youla.ru call forwarding'],
    ['ym', 'youla.ru'],
    ['rl', 'inDriver'],
    ['aaa', 'Nubank'],
    ['aik', 'ZUS Coffee'],
    ['xh', 'OVO'],
    ['mo', 'Bumble'],
    ['do', 'Leboncoin'],
    ['ep', 'Temu'],
    ['wr', 'Walmart'],
    ['abq', 'Upwork'],
    ['vm', 'OkCupid'],
    ['gp', 'Ticketmaster'],
    ['ua', 'BlaBlaCar'],
    ['cy', 'РСА'],
    ['ace', 'Tata Neu'],
    ['agt', 'Uralairlines'],
    ['bd', 'X5ID'],
    ['aor', 'OKX'],
    ['acm', 'Razer'],
    ['aet', 'Greywoods'],
    ['aav', 'Alchemy'],
    ['gj', 'Carousell'],
    ['hs', 'Asda'],
    ['za', 'JDcom'],
    ['lj', 'Santander'],
    ['zs', 'Bilibili'],
    ['da', 'MTS CashBack'],
    ['ie', 'bet365'],
    ['vd', 'Betfair'],
    ['hu', 'Ukrnet'],
    ['agm', 'CMB'],
    ['ah', 'EscapeFromTarkov'],
    ['wh', 'TanTan'],
    ['ke', 'Эльдорадо'],
    ['xk', 'DiDi'],
    ['cn', 'Fiverr'],
    ['aiz', 'Brevo'],
    ['kl', 'kolesa.kz'],
    ['tc', 'Rambler'],
    ['mv', 'Fruitz'],
    ['xd', 'Tokopedia'],
    ['nc', 'Payoneer'],
    ['cp', 'Uklon'],
    ['agx', 'MeiQFashion'],
    ['aoh', 'ЮMoney'],
    ['nt', 'Sravni'],
    ['ng', 'FunPay'],
    ['abe', 'Foodora'],
    ['vg', 'ShellBox'],
    ['ns', 'Oldubil'],
    ['gq', 'Freelancer'],
    ['xs', 'GroupMe'],
    ['bl', 'BIGO LIVE'],
    ['xy', 'Depop'],
    ['lm', 'FarPost'],
    ['bo', 'Wise'],
    ['abx', 'Kaching'],
    ['abl', 'gpnbonus'],
    ['aba', 'Rappi'],
    ['dj', 'LUKOIL-AZS'],
    ['hb', 'Twitch'],
    ['hc', 'MOMO'],
    ['rd', 'Lenta'],
    ['cm', 'Prom'],
    ['yx', 'JTExpress'],
    ['aoa', 'Hicard'],
    ['ue', 'Onet'],
    ['ex', 'Linode'],
    ['afn', 'roomster'],
    ['abh', 'UOL Host'],
    ['re', 'Coinbase'],
    ['dn', 'Paxful'],
    ['agz', 'Jiva Petani'],
    ['acu', 'CityMall'],
    ['jq', 'Paysafecard'],
    ['cb', 'Bazos'],
    ['fv', 'Vidio'],
    ['jl', 'Hopi'],
    ['ta', 'Wink'],
    ['aob', 'Anthropic'],
    ['apm', 'Index'],
    ['at', 'Perfluence'],
    ['jc', 'IVI'],
    ['akt', 'xworldwallet'],
    ['ane', 'Supercell'],
    ['tl', 'Truecaller'],
    ['ahe', 'Bunq'],
    ['ae', 'myGLO'],
    ['aeu', 'TheFork'],
    ['aff', 'C6 Bank'],
    ['kv', 'Rush'],
    ['aee', 'Amway'],
    ['zp', 'Pinduoduo'],
    ['fz', 'KFC'],
    ['sh', 'Vkusvill'],
    ['kz', 'NimoTV'],
    ['be', 'СберМегаМаркет'],
    ['zl', 'Airtel'],
    ['acw', 'YouDo'],
    ['abg', 'PagBank'],
    ['zb', 'FreeNow'],
    ['rt', 'hily'],
    ['mx', 'SoulApp'],
    ['afz', 'Klarna'],
    ['xt', 'Flipkart'],
    ['ib', 'Immowelt'],
    ['zg', 'Setel'],
    ['aq', 'Glovo'],
    ['em', 'ZéDelivery'],
    ['gr', 'Astropay'],
    ['ls', 'Careem'],
    ['tn', 'LinkedIN'],
    ['zo', 'Kaggle'],
    ['vs', 'WinzoGame'],
    ['adv', 'Cian'],
    ['zm', 'OfferUp'],
    ['vp', 'Kwai'],
    ['abj', 'Serasa'],
    ['afs', 'Privalia'],
    ['sd', 'dodopizza'],
    ['ada', 'TRUTH SOCIAL'],
    ['agk', 'Ipsos iSay'],
    ['dt', 'Delivery Club'],
    ['abo', 'WEBDE'],
    ['ann', 'Bradesco'],
    ['uf', 'Eneba'],
    ['dp', 'ProtonMail'],
    ['ajn', 'Gopuff'],
    ['gu', 'Fora'],
    ['amy', 'Отзовик'],
    ['ol', 'KazanExpress'],
    ['qv', 'Badoo'],
    ['yj', 'eWallet'],
    ['ha', 'My11Circle'],
    ['ij', 'Revolut'],
    ['wg', 'Skout'],
    ['br', 'Вкусно и Точка'],
    ['lp', 'Algida'],
    ['pu', 'Justdating'],
    ['et', 'Clubhouse'],
    ['mw', 'Transfergo'],
    ['rj', 'Детский мир'],
    ['abd', 'BeBoo'],
    ['ahb', 'Ubisoft'],
    ['acb', 'Spark Driver'],
    ['afk', 'Chevron'],
    ['adw', 'Профи'],
    ['aje', 'CupidMedia'],
    ['ee', 'Twilio'],
    ['als', 'Greggs'],
    ['ce', 'mosru'],
    ['ajj', 'Rebtel'],
    ['abu', 'BPJSTK'],
    ['yu', 'Xiaomi'],
    ['ch', 'Pocket52'],
    ['fs', 'Şikayet var'],
    ['qx', 'WorldRemit'],
    ['afi', 'Ame Digital'],
    ['apk', 'Liberty'],
    ['ge', 'Paytm'],
    ['alm', 'Muzz'],
    ['xz', 'paycell'],
    ['nl', 'Myntra'],
    ['yy', 'Venmo'],
    ['co', 'Rediffmail'],
    ['kk', 'Idealista'],
    ['hx', 'AliExpress'],
    ['mz', 'Zolushka'],
    ['qh', 'Oriflame'],
    ['ms', 'NovaPoshta'],
    ['lc', 'Subito'],
    ['ct', 'КухняНаРайоне'],
    ['fk', 'BLIBLI'],
    ['aly', 'Bebeclub'],
    ['xx', 'Joyride'],
    ['qe', 'GG'],
    ['oe', 'Codashop'],
    ['bx', 'Dosi'],
    ['jx', 'Swiggy'],
    ['kj', 'YAPPY'],
    ['ud', 'Disney Hotstar'],
    ['dy', 'Zomato'],
    ['tk', 'МВидео'],
    ['acv', 'A23'],
    ['pr', 'Trendyol'],
    ['ahc', 'START'],
    ['uz', 'OffGamers'],
    ['aaz', 'Ozan'],
    ['agd', 'Grailed'],
    ['yg', 'CourseHero'],
    ['adp', 'Cabify'],
    ['km', 'Rozetka'],
    ['agg', 'OneForma'],
    ['abw', 'SOKOLOV'],
    ['ais', 'Schibsted'],
    ['gk', 'AptekaRU'],
    ['agj', 'Marktplaats'],
    ['akr', 'Voi'],
    ['abc', 'Taptap Send'],
    ['aix', 'Move It'],
    ['anw', 'Premmia'],
    ['aeh', 'Аптека Апрель'],
    ['afy', 'Tuul'],
    ['tr', 'Paysend'],
    ['anx', 'InfinitePay'],
    ['bn', 'Alfagift'],
    ['xr', 'Tango'],
    ['adc', 'PlayOJO'],
    ['agl', 'Betano'],
    ['ama', 'WooPlus'],
    ['ti', 'cryptocom'],
    ['aej', 'Autoru'],
    ['anl', 'AttaPoll'],
    ['ov', 'Beget'],
    ['amb', 'Vercel'],
    ['qg', 'MoneyPay'],
    ['aem', 'AstraPay'],
    ['agc', 'VIMpay'],
    ['aon', 'Binance'],
    ['anf', 'ZoomInfo'],
    ['rc', 'Skype'],
    ['oz', 'Poshmark'],
    ['agp', 'hdfcbank'],
    ['aes', 'Золотое Яблоко'],
    ['ano', 'Shopify'],
    ['ady', 'ТОКИО-CITY'],
    ['ang', 'TOMORO COFFEE'],
    ['il', 'IQOS'],
    ['aoe', 'Sendwave'],
    ['bs', 'TradeUP'],
    ['fj', 'Potato Chat'],
    ['anq', 'Hitnspin'],
    ['bk', 'G2G'],
    ['alv', 'TIER'],
    ['aov', 'Zanimaika'],
    ['yh', 'hh'],
    ['ahl', 'Maxim'],
    ['ani', 'Talabat'],
    ['ze', 'Shpock'],
    ['acg', 'KoronaPay'],
    ['afo', 'KION'],
    ['qr', 'MEGA'],
    ['sb', 'Lamoda'],
    ['ul', 'Getir'],
    ['apc', 'iGameBUY'],
    ['kh', 'Bukalapak'],
    ['vr', 'MotorkuX'],
    ['yi', 'Yemeksepeti'],
    ['ahr', 'This Fate'],
    ['io', 'ЗдравСити'],
    ['jv', 'Consultant'],
    ['st', 'Auchan'],
    ['amz', 'ImmoScout24'],
    ['wd', 'CasinoPlus'],
    ['gm', 'Mocospace'],
    ['os', 'Dhani'],
    ['ff', 'AVON'],
    ['ank', 'Garena'],
    ['wz', 'FoxFord'],
    ['aol', 'Paysera'],
    ['ml', 'ApostaGanha'],
    ['sv', 'Dostavista'],
    ['adu', 'Seznam'],
    ['anb', 'Abastece-aí'],
    ['ih', 'TeenPattiStarpro'],
    ['we', 'DrugVokrug'],
    ['jh', 'PingPong'],
    ['zr', 'Papara'],
    ['aaq', 'Netease'],
    ['fg', 'IndianOil'],
    ['aii', 'Hinge Dating'],
    ['iq', 'icq'],
    ['zj', 'ROBINHOOD'],
    ['aom', 'Monzo'],
    ['po', 'premium.one'],
    ['sz', 'Pivko24'],
    ['kx', 'Vivo'],
    ['qy', 'Zhihu'],
    ['aja', 'G2A'],
    ['mc', 'Michat'],
    ['uy', 'Meliuz'],
    ['adi', 'Zepto'],
    ['apl', 'Sideline'],
    ['fh', 'Lalamove'],
    ['ln', 'Grofers'],
    ['og', 'Okko'],
    ['rn', 'neftm'],
    ['alq', 'Etsy'],
    ['abf', 'Parimatch'],
    ['dd', 'CloudChat'],
    ['ik', 'GuruBets'],
    ['acc', 'LuckyLand Slots'],
    ['sm', 'YoWin'],
    ['zx', 'CommunityGaming'],
    ['adj', 'RummyCircle'],
    ['amc', 'Fortune Slots'],
    ['fi', 'Dundle'],
    ['yq', 'mail.com'],
    ['ain', 'SpaceWeb'],
    ['gg', 'PagSmile'],
    ['it', 'CashApp'],
    ['hh', 'Uplay'],
    ['aqf', 'Coze'],
    ['wp', '163СOM'],
    ['vb', 'Кораблик'],
    ['xu', 'RecargaPay'],
    ['aml', 'Xbox'],
    ['apr', 'Capital One'],
    ['tm', 'Akulaku'],
    ['aip', 'AfreecaTV'],
    ['ix', 'Celcoin'],
    ['aa', 'Probo'],
    ['cg', 'Gemgala'],
    ['hi', 'JungleeRummy'],
    ['py', 'Monese'],
    ['tf', 'Noon'],
    ['dg', 'Mercari'],
    ['fw', '99acres'],
    ['bu', 'MonobankIndia'],
    ['so', 'RummyWealth'],
    ['vc', 'Banqi'],
    ['xv', 'Wish'],
    ['abb', 'Coca-Cola'],
    ['ads', 'GoChat'],
    ['aps', 'Skelbiu'],
    ['ko', 'AdaKami'],
    ['wc', 'Craigslist'],
    ['anv', 'Shield'],
    ['ly', 'Olacabs'],
    ['xl', 'Wmaraci'],
    ['fe', 'CliQQ'],
    ['hl', 'Band'],
    ['qd', 'Taobao'],
    ['anj', 'Gemini'],
    ['fx', 'PGbonus'],
    ['fx', 'PGbonus call forwarding'],
    ['rf', 'Akudo'],
    ['ach', 'Плайт'],
    ['aok', 'NETELLER'],
    ['gw', 'CallApp'],
    ['adt', 'willhaben'],
    ['cw', 'PaddyPower'],
    ['tp', 'IndiaGold'],
    ['bm', 'MarketGuru'],
    ['us', 'IRCTC'],
    ['aag', 'Pockit'],
    ['apj', 'Tinkoff VoiceKit'],
    ['th', 'WestStein'],
    ['aih', 'Fups'],
    ['ip', 'Burger King'],
    ['wt', 'IZI'],
    ['bp', 'GoFundMe'],
    ['vj', 'Stormgain'],
    ['ui', 'RuTube'],
    ['aiv', 'Striving in the Lion City'],
    ['az', 'CityBase'],
    ['acs', 'Tata CLiQ Palette'],
    ['alk', 'HUGESoft'],
    ['pv', 'Koshelek'],
    ['aph', 'Openbudget'],
    ['iv', 'Inboxlv'],
    ['wj', '1хbet'],
    ['aow', 'Geekay'],
    ['eu', 'LiveScore'],
    ['aco', 'AR Lens'],
    ['apa', 'Exness'],
    ['ox', 'Damejidlo'],
    ['ahg', 'Credcesta'],
    ['abn', 'Bybit'],
    ['ajv', 'ShareParty'],
    ['gl', 'GlobalTel'],
    ['ty', 'Окей'],
    ['ajf', 'iPanelOnline'],
    ['ye', 'ZaleyCash'],
    ['ajp', 'AsiaMiles'],
    ['lw', 'MrGreen'],
    ['ajm', 'Gener8'],
    ['agw', 'Adverts'],
    ['adm', 'FitCredit'],
    ['jo', 'SticPay'],
    ['aio', 'Prakerja'],
    ['np', 'Siply'],
    ['anu', 'Edurators'],
    ['pn', 'CoffeeLike'],
    ['ajq', 'MyValue'],
    ['wq', 'Leboncoin1'],
    ['nb', 'Верный'],
    ['cs', 'AgriDevelop'],
    ['ajx', 'Kemnaker RI'],
    ['aqn', 'CashMyPic'],
    ['lb', 'Mailru Group'],
    ['nr', 'Tosla'],
    ['pt', 'Bitaqaty'],
    ['kd', 'Author24'],
    ['lx', 'DewuPoison'],
    ['age', 'MTR Mobile'],
    ['yd', '米画师Mihuashi'],
    ['adb', 'PoshVine'],
    ['ro', 'PingCode'],
    ['aga', 'Publi24'],
    ['aen', 'Madslots'],
    ['aea', 'HungryPanda'],
    ['adn', 'Janganana'],
    ['aie', 'Фотострана'],
    ['lu', 'Crickpe'],
    ['eh', 'Telegram 2.0'],
    ['aof', 'Guzman y Gomez'],
    ['aed', 'Booking.com'],
    ['up', 'Magnolia'],
    ['ail', 'Zoo Game'],
    ['ca', 'SuperS'],
    ['zu', 'BigC'],
    ['oy', 'CashFly'],
    ['hf', 'Cleartrip'],
    ['aei', 'Sharyat'],
    ['op', 'MIRATORG'],
    ['rw', 'BLS-SPAIN'],
    ['aqa', 'Satori'],
    ['amm', 'punjab citizen'],
    ['aqk', 'Richkart'],
    ['adf', 'Punjab Timber Traders'],
    ['wn', 'GameArena'],
    ['aeg', 'Flowwow'],
    ['aig', 'K11'],
    ['nq', 'Trip'],
    ['nu', 'Stripe'],
    ['zz', 'DENT'],
    ['kq', 'FotoCasa'],
    ['amg', 'SBI Card'],
    ['aft', 'Neocrypto'],
    ['eg', 'ContactSys'],
    ['bb', 'LazyPay'],
    ['aid', 'Kia'],
    ['bt', 'Alfa'],
    ['alz', 'CasinoAndFriends'],
    ['en', 'Hermes'],
    ['iw', 'MyLavash'],
    ['aew', 'Flip'],
    ['akp', 'Her'],
    ['akm', 'LOTTE Mart'],
    ['aer', 'PlayerAuctions'],
    ['ay', 'Ruten'],
    ['api', 'KKTIX'],
    ['qm', 'RosaKhutor'],
    ['qu', 'Agroinform'],
    ['rs', 'Lotus'],
    ['ps', 'Zdorov'],
    ['afl', 'Vsesmart'],
    ['hn', '1688'],
    ['ahn', 'Рив Гош'],
    ['yp', 'Payzapp'],
    ['ael', 'Cloud Manager'],
    ['agh', 'Anibis'],
    ['aiq', 'Prime Opinion'],
    ['ajl', 'av100pro'],
    ['aht', 'MockGuru'],
    ['sx', 'Crowdtap'],
    ['ago', 'Servify'],
    ['ao', 'UU163'],
    ['ale', 'Lydia'],
    ['ny', 'Pyro Music'],
    ['xe', 'GalaxyChat'],
    ['ra', 'KeyPay'],
    ['kg', 'FreeChargeApp'],
    ['fq', 'Контур'],
    ['amf', 'Acko'],
    ['vh', 'Штолле'],
    ['ake', 'DIKIDI'],
    ['aki', 'tiketcom'],
    ['anh', 'Cadbury'],
    ['aju', 'Daya Auto'],
    ['cl', 'UWIN'],
    ['sp', 'HappyFresh'],
    ['sa', 'AGIBANK'],
    ['aay', 'JioMart'],
    ['cd', 'SpotHit'],
    ['di', 'Loanflix'],
    ['px', 'Nifty'],
    ['aab', 'BharatPe'],
    ['dm', 'Iwplay'],
    ['qn', 'Blued'],
    ['adg', 'Yono777'],
    ['vx', 'HeyBox'],
    ['od', 'FWDMAX'],
    ['aby', 'ITMS'],
    ['lg', 'MediBuddy'],
    ['uh', 'Yubo'],
    ['lv', 'Megogo'],
    ['aex', 'Neon'],
    ['akx', 'Sony LIV'],
    ['fy', 'Mylove'],
    ['adq', 'Uzum'],
    ['mu', 'MyMusicTaste'],
    ['ali', 'StockyDodo'],
    ['zf', 'OnTaxi'],
    ['ahj', 'Strato'],
    ['sq', 'KuCoinPlay'],
    ['te', 'eFood'],
    ['vn', 'Yaay'],
    ['alj', 'Spotify'],
    ['wf', 'YandexGo'],
    ['aqp', 'Golden Plus GP'],
    ['jz', 'Kaya'],
    ['aap', 'Tiptapp'],
    ['si', 'Cita Previa'],
    ['xo', 'Notifire'],
    ['hy', 'Ininal'],
    ['je', 'Nanovest'],
    ['bv', 'Metro'],
    ['afb', 'Nebu'],
    ['sl', 'СберАптека'],
    ['ri', 'BillMill'],
    ['amr', 'Univest'],
    ['lk', 'PurePlatfrom'],
    ['ald', 'Nice88'],
    ['kp', 'HQ Trivia'],
    ['bg', 'MIXMART'],
    ['qb', 'Payberry'],
    ['alp', 'Mera Gaon'],
    ['uc', 'Tatneft'],
    ['ajb', 'Бери заряд'],
    ['om', 'Corona'],
    ['alg', 'Ankama'],
    ['acr', 'QwikCilver'],
    ['la', 'ssoidnet'],
    ['apo', 'Netmarble'],
    ['cc', 'Quipp'],
    ['mh', 'Ашан'],
    ['afj', 'Laybuy'],
    ['agy', 'Baihe'],
    ['apw', 'Bankiros'],
    ['he', 'Mewt'],
    ['lr', 'Okta'],
    ['yz', 'Около'],
    ['apt', 'Airwallex'],
    ['ant', 'Cashew'],
    ['aqj', 'Vanaasthal'],
    ['abs', 'Playerzpot'],
    ['oj', 'LoveRu'],
    ['jt', 'TurkiyePetrolleri'],
    ['amj', 'm panels'],
    ['alx', 'NutriClub'],
    ['adz', 'Шоколадница'],
    ['ky', 'SpatenOktoberfest'],
    ['pj', 'Podeli'],
    ['air', 'TipTip'],
    ['kr', 'Eyecon'],
    ['xg', 'FortunaSK'],
    ['zd', 'Zilch'],
    ['ho', 'Cathay'],
    ['ii', 'CashKaro'],
    ['ajo', 'CoffeeTea'],
    ['mp', 'Winmasters'],
    ['jf', 'Likee'],
    ['ahz', 'Кузбасс Онлайн'],
    ['amt', 'Moneyview'],
    ['aql', 'Xigua Video 西瓜视频'],
    ['kw', 'Foody'],
    ['alo', 'Profee'],
    ['rq', 'AptekiPlus'],
    ['ld', 'Cashmine'],
    ['sy', 'Brahma'],
    ['qp', 'Максавит'],
    ['ow', 'RegRu'],
    ['aog', 'Naukri'],
    ['zn', 'Biedronka'],
    ['um', 'Belwest'],
    ['ci', 'redBus'],
    ['ahv', 'Surveybell'],
    ['aot', 'Diversity'],
    ['rx', 'Sheerid'],
    ['ga', 'Roposo'],
    ['alt', 'Segari'],
    ['aep', 'Slickcall'],
    ['aev', 'BankKaro'],
    ['acf', 'Winter Loan'],
    ['iy', 'FoodHub'],
    ['ef', 'Nextdoor'],
    ['abr', 'Privy'],
    ['yb', 'Система Город'],
    ['gi', 'Hotline'],
    ['db', 'ezbuy'],
    ['akj', 'Easycash'],
    ['es', 'iQIYI'],
    ['er', 'Kwork'],
    ['tt', 'Ziglu'],
    ['sk', 'Skroutz'],
    ['amp', 'VerifyKit'],
    ['ht', 'Bitso'],
    ['hj', 'Stoloto'],
    ['afq', 'MagaLu'],
    ['nj', 'FreshKarta'],
    ['xb', 'RummyOla'],
    ['bf', 'Keybase'],
    ['anc', 'VARUS'],
    ['ade', 'Magicpin'],
    ['aoi', 'Cryptonow'],
    ['du', 'AUBANK'],
    ['amo', 'CoinFantasy'],
    ['ey', 'miloan'],
    ['ahp', 'PizzaHut'],
    ['sc', 'Voggt'],
    ['ab', 'Alibaba'],
    ['zq', 'IndiaPlays'],
    ['anp', 'Blackcatcard'],
    ['eb', 'Voltz'],
    ['akk', 'Dagangan'],
    ['ec', 'RummyCulture'],
    ['dv', 'NoBroker'],
    ['anm', 'CaltexGO'],
    ['oh', 'MapleSEA'],
    ['agb', 'Smiles'],
    ['fc', 'PharmEasy'],
    ['zw', 'Quack'],
    ['lt', 'BitClout'],
    ['bj', 'Вита экспресс'],
    ['apu', 'LIC Games'],
    ['hz', 'Drom'],
    ['jw', 'Br777'],
    ['acd', 'Cloud.ru'],
    ['ne', 'Coindcx'],
    ['alb', 'Guiche Web'],
    ['ags', 'Abbott'],
    ['aky', 'GOMOFY'],
    ['afh', 'mPokket'],
    ['aez', 'Shein'],
    ['ws', 'Indodax'],
    ['rm', 'Faberlic'],
    ['ar', 'Wondermart'],
    ['aeo', 'Allofresh'],
    ['amn', 'constitutioner'],
    ['gc', 'TradingView'],
    ['pb', 'SkyTV'],
    ['apf', 'Carrefour'],
    ['ajg', 'Fortumo'],
    ['yf', 'Citymobil'],
    ['aqm', 'Tala'],
    ['aiy', 'nloto'],
    ['qo', 'Moneylion'],
    ['xw', 'Taki'],
    ['uv', 'BinBin'],
    ['aax', 'Boyaa'],
    ['pq', 'CDkeys'],
    ['act', 'Maxis'],
    ['qz', 'Faceit'],
    ['akc', 'Paybis'],
    ['tz', 'Лейка'],
    ['apy', 'Винлаб'],
    ['apb', 'eToro'],
    ['alc', 'Facily'],
    ['qc', 'Праймериз 2020'],
    ['aoq', 'JB Hi-Fi'],
    ['amq', 'FRESHOOS'],
    ['amk', 'GORDAN'],
    ['ajt', 'Город'],
    ['ck', 'BeReal'],
    ['ajw', 'INDOBA'],
    ['nk', 'Gittigidiyor'],
    ['yv', 'IPLwin'],
    ['mi', 'Zupee'],
    ['aks', 'Hanya'],
    ['aic', 'Whoscall'],
    ['aou', 'IT Business Group'],
    ['agr', 'Yonogames'],
    ['ia', 'Socios'],
    ['au', 'Haraj'],
    ['nn', 'Giftcloud'],
    ['afr', 'Ultragaz'],
    ['anz', 'TopGun'],
    ['apg', 'Damai'],
    ['hp', 'Meesho'],
    ['ajr', 'boku'],
    ['wv', 'AIS'],
    ['ajk', 'Venteny'],
    ['dk', 'Pairs'],
    ['amx', 'TANK'],
    ['se', 'Feeld'],
    ['bi', '勇仕网络Ys4fun'],
    ['adl', 'EarnEasy'],
    ['ack', 'RegainRX'],
    ['aoy', 'PLN Mobile'],
    ['aln', 'Remotasks'],
    ['pg', 'NRJ Music Awards'],
    ['vo', 'Brand20ua'],
    ['amw', 'Tise'],
    ['aoz', 'ReclameAQUI'],
    ['sw', 'NCsoft'],
    ['ajz', 'MotionPay'],
    ['rg', 'Porbet'],
    ['va', 'SportGully'],
    ['hk', '4Fun'],
    ['gs', 'SamsungShop'],
    ['sr', 'Starbucks'],
    ['ajy', 'All Access'],
    ['aoj', 'Simply'],
    ['afc', 'Bunda'],
    ['sf', 'SneakersnStuff'],
    ['aqg', 'Publix'],
    ['afe', 'GovBr'],
    ['js', 'GolosZa'],
    ['zv', 'Digikala'],
    ['acl', 'swissmoney'],
    ['gx', 'Hepsiburadacom'],
    ['fa', 'XadrezFeliz'],
    ['akn', 'Chakra Rewards'],
    ['aif', 'Royal Canin'],
    ['ado', 'Jasper Home Fashions'],
    ['fp', 'Phound'],
    ['no', 'Virgo'],
    ['zt', 'Budweiser'],
    ['vv', 'Seosprint'],
    ['adx', 'FirstCry'],
    ['hm', 'Globus'],
    ['acn', 'Radium'],
    ['abm', 'Утконос'],
    ['el', 'Bisu'],
    ['fl', 'RummyLoot'],
    ['abv', 'PlayZone'],
    ['akh', 'Prenagen Club'],
    ['gy', 'MIYACHAT'],
    ['ahd', 'OpenPhone'],
    ['alr', 'Vson'],
    ['gz', 'LYKA'],
    ['aka', 'LinkAja'],
    ['rk', 'Fotka'],
    ['gh', 'GyFTR'],
    ['ed', 'Gamer'],
    ['uw', 'Kirana'],
    ['ahm', 'BRO'],
    ['aeb', 'Shine Brand Seeds'],
    ['agq', 'Bajaj Finserv'],
    ['aos', 'Loloo'],
    ['de', 'Karusel'],
    ['aoo', 'Pegasus Airlines'],
    ['acj', 'TeriMeriChoice'],
    ['wl', 'YouGotaGift'],
    ['uo', 'CafeBazaar'],
    ['ako', 'Ryde'],
    ['akb', 'Gurmanika'],
    ['ba', 'Expressmoney'],
    ['ww', 'BIP'],
    ['aek', 'EnerGO'],
    ['adk', 'Khatabook'],
    ['iu', 'Bykea'],
    ['ji', 'Monobank'],
    ['aiu', 'GetNinjas'],
    ['amh', 'MitID'],
    ['ej', 'MrQ'],
    ['cu', '炙热星河'],
    ['ahs', '1and1'],
    ['xn', 'Familia'],
    ['aaw', 'Aya Bank'],
    ['afg', 'Luck'],
    ['ic', 'JoGo'],
    ['oc', 'DealShare'],
    ['ve', 'Dream11'],
    ['app', 'ClassPass'],
    ['akq', 'Blank Street'],
    ['ait', 'FeetFinder'],
    ['tj', 'dbrUA'],
    ['akg', 'Book My Play'],
    ['mr', 'Fastmail'],
    ['cv', 'WashXpress'],
    ['qa', 'MyFishka'],
    ['ahy', 'Fliff'],
    ['ame', 'Discover Hong Kong'],
    ['ams', 'GlowRoad'],
    ['fm', 'Touchance'],
    ['agu', 'Marlboro'],
    ['wy', 'Yami'],
    ['acq', 'Astha Tea'],
    ['agn', 'Flik'],
    ['aeq', 'Godrej'],
    ['nm', 'Thisshop'],
    ['mk', 'LongHu'],
    ['mn', 'RRSA'],
    ['nh', 'AlloBank'],
    ['ku', 'RoyalWin'],
    ['aas', 'XXGame'],
    ['vl', 'Ортека'],
    ['ez', 'GoerliFaucet'],
    ['lo', 'OPPO'],
    ['aho', 'UangMe'],
    ['mf', 'Weidian'],
    ['vq', 'LadyMaria'],
    ['aj', 'OneAset'],
    ['vf', 'Q12 Trivia'],
    ['lh', '24betting'],
    ['aox', 'Aukro'],
    ['pw', 'SellMonitor'],
    ['apn', 'Beboo'],
    ['wm', '99Speed'],
    ['xc', 'SynotTip'],
    ['acp', 'BonusLink'],
    ['zi', 'LoveLocal'],
    ['aec', 'AaHIRA Fashion'],
    ['akw', 'WINDS'],
    ['yo', 'Amasia'],
    ['an', 'Adidas'],
    ['aji', 'МИГРАНТ СЕРВИС'],
    ['aca', 'Sunlight'],
    ['cj', 'Dotz'],
    ['ai', 'CELEBe'],
    ['acy', 'Airtime'],
    ['oq', 'Vlife'],
    ['rv', 'Kotak811'],
    ['jn', 'CloudBet'],
    ['pz', 'Lidl'],
    ['pp', 'Huya'],
    ['qk', 'Bit'],
    ['agf', 'Meitu'],
    ['jy', 'Sorare'],
    ['ph', 'SnappFood'],
    ['le', 'E bike Gewinnspiel'],
    ['xa', 'УлыбкаРадуги'],
    ['apq', 'WePoker'],
    ['ll', '888casino'],
    ['ak', 'Douyu'],
    ['adh', 'Frizza'],
    ['ajh', 'WAUG'],
    ['dc', 'YikYak'],
    ['cz', 'Getmega'],
    ['aim', 'Firebase'],
    ['aau', 'RockeTreach'],
    ['nw', 'Ximalaya'],
    ['ahi', 'Daki'],
    ['amd', 'Smart'],
    ['eo', 'Sizeer'],
    ['ami', 'TEAMORU'],
    ['ahh', 'Cumbuca'],
    ['yk', 'СпортМастер'],
    ['pl', 'Перекресток'],
    ['ahx', 'Bitrue'],
    ['xp', 'MonetaRu'],
    ['ut', 'Энергобум'],
    ['rz', 'EasyPay'],
    ['aqd', 'Pesohere'],
    ['af', 'TradeX'],
    ['vw', 'CoinField'],
    ['aar', 'Bearwww'],
    ['hq', 'Magicbricks'],
    ['aci', 'СберЗдоровье'],
    ['wk', 'Mobile01'],
    ['gv', 'Humta'],
    ['agv', 'DoneDeal'],
    ['ea', 'JamesDelivery'],
    ['aqh', 'Rayobyte'],
    ['cr', 'TenChat'],
    ['qt', 'MoneyСontrol'],
    ['any', 'FastEarn'],
    ['afw', 'Packeta'],
    ['aij', 'NEQUI'],
    ['jp', 'Rbt'],
    ['dw', 'Divar'],
    ['ss', 'hezzl'],
    ['aqo', 'xREWARD'],
    ['gb', 'YouStar'],
    ['qs', 'МирЗнакомств'],
    ['hg', 'Switips'],
    ['aef', 'Long Drive Cars'],
    ['jd', 'GiraBank'],
    ['ja', 'Weverse'],
    ['cx', 'Icrypex'],
    ['ana', 'Sicredi'],
    ['jj', 'Aitu'],
    ['afx', 'Gamesofa'],
    ['yn', 'Allegro'],
    ['fo', 'MobiKwik'],
    ['apd', '2dehands'],
    ['adr', 'Boosty'],
    ['ajd', 'Bankera'],
    ['iz', 'Global24'],
    ['vt', 'Innomax'],
    ['qi', '32red'],
    ['ql', 'CMTcuzdan'],
    ['dz', 'Dominos Pizza'],
    ['uq', 'TopDetal'],
    ['hr', 'JKF'],
    ['aqi', 'Cairon Fashion'],
    ['td', 'ChaingeFinance'],
    ['tv', 'Flink'],
    ['alw', 'Vida'],
    ['xf', 'LightChat'],
    ['ur', 'MyDailyCash'],
    ['ahq', 'SEEDS'],
    ['lz', 'Things'],
    ['ks', 'Hirect'],
    ['hd', 'MarketPapa'],
    ['jb', 'Wing Money'],
    ['afa', 'CDEK'],
    ['zy', 'Nttgame'],
    ['alh', 'Lion Parcel'],
    ['akd', 'Feels'],
    ['uj', 'СhampionСasino'],
    ['ys', 'ZCity'],
    ['gt', 'Gett'],
    ['rp', 'hamrahaval'],
    ['ei', 'Taksheel'],
    ['un', 'humblebundle'],
    ['oo', 'LigaPro'],
    ['ahw', 'Zasilkovna'],
    ['abp', 'D5BET'],
    ['apz', 'Wynk'],
    ['ru', 'HOP'],
    ['aha', 'Angel One'],
    ['amu', 'Glassbox'],
    ['abi', 'BytePlus'],
    ['sj', 'HandyPick'],
    ['ala', 'GetResponse'],
    ['lq', 'Potato'],
    ['aw', 'Taikang'],
    ['aat', 'TamTam'],
    ['ahk', 'БлинБери'],
    ['xi', 'InFund'],
    ['ahf', 'Fugeelah'],
    ['gn', 'A9A'],
    ['ug', 'Fiqsy'],
    ['afv', 'Джилекс'],
    ['gd', 'Surveytime'],
    ['qj', 'Whoosh'],
    ['dx', 'Powerkredite'],
    ['amv', 'MeSeems'],
    ['mq', 'GMNG'],
    ['pa', 'Gamekit'],
    ['su', 'LOCO'],
    ['afu', 'ВсеИнструменты'],
    ['ry', 'McDonalds'],
    ['ajs', 'GetPlus'],
    ['bh', 'Uteka'],
    ['agi', 'Njuškalo'],
    ['afd', 'Astra Otoshop'],
    ['abt', 'ArenaPlus'],
    ['bq', 'Adani'],
    ['rb', 'Tick'],
    ['jm', 'mzadqatar'],
    ['ux', 'Домовой'],
    ['dq', 'IceCasino'],
    ['xq', 'MPL'],
    ['wu', 'PrivetMir'],
    ['ou', 'Gabi'],
    ['cf', 'irancell'],
    ['akz', 'Panvel'],
    ['wo', 'Parkplus'],
    ['alf', 'WEBULL'],
    ['alu', 'BC Game'],
    ['aiw', 'СушиВёсла'],
    ['kn', 'Verse'],
    ['ape', 'Toutiao'],
    ['afp', 'VFS GLOBAL'],
    ['acx', 'VCollective'],
    ['abz', 'Дарить Легко'],
    ['akl', 'DOKU'],
    ['eq', 'Qoo10'],
    ['akf', 'Ollis'],
    ['aey', 'Next'],
    ['kb', 'kufarby'],
    ['tq', 'Swvl'],
    ['ajc', 'Почта России'],
    ['rh', 'Ace2Three'],
    ['ob', 'Onlinerby'],
]
